# This dev environment will hookup to a private geth chain to allow
# local testing.
version: "3.8"
services:
  snode:
    image: blocknetdx/servicenode:latest
    entrypoint: /opt/blockchain/start-snode.sh
    restart: unless-stopped
    environment:
      PUBLIC_IP: "${PUBLIC_IP}"
      RPC_USER: "${RPC_USER}"
      RPC_PASSWORD: "${RPC_PASSWORD}"
      SN_NAME: "${SN_NAME}"
      SN_ADDRESS: "${SN_ADDRESS}"
      SN_KEY: "${SN_KEY}"
    volumes:
      - snode-config:/opt/blockchain/config
      - snode-data:/opt/blockchain/data
      - type: bind
        source: ./scripts
        target: /opt/blockchain
      - type: bind
        source: ./plugins
        target: /opt/blockchain/data/plugins
    ports:
      - "41412:41412"
      - "41414:41414"
    networks:
      backend_dev:
        ipv4_address: 172.30.0.2

  geth:
    image: blocknetdx/client-go:dev
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: "--datadir /opt/blockchain/data --nousb --allow-insecure-unlock --networkid 41412 --netrestrict 172.17.0.0/24 --netrestrict 172.30.0.0/24 --netrestrict 172.31.0.0/24 --netrestrict 192.168.1.0/24 --http --http.api personal,eth,net,web3 --http.addr 0.0.0.0 --ws --ws.api personal,eth,net,web3 --ws.addr 0.0.0.0 --nodiscover"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    networks:
      backend_dev:
        ipv4_address: 172.30.0.3

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eth
      POSTGRES_USER: ethproxy
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      backend_dev:
        ipv4_address: 172.30.0.4

  eth_payment_api:
    image: blocknetdx/eth-payment-processor:0.5.2
    restart: unless-stopped
    environment:
      ETH_HOST: 172.30.0.3
      ETH_PORT: 8546
      PAYMENT_AMOUNT_TIER1: 35
      PAYMENT_AMOUNT_TIER2: 200
      DB_HOST: 172.30.0.4
      DB_USERNAME: ethproxy
      DB_PASSWORD: password
      DB_DATABASE: eth
    expose:
      - 8080
    depends_on:
      - geth
      - postgresql
    networks:
      backend_dev:
        ipv4_address: 172.30.0.5

  xr_proxy:
    image: blocknetdx/exrproxy:0.7.9
    entrypoint: /opt/scripts/start-xrproxy.sh
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      RPC_USER: "${RPC_USER}"
      RPC_PASSWORD: "${RPC_PASSWORD}"
      SN_KEY: "${SN_KEY}"
      PAYMENT_PROCESSOR_HOST: 172.30.0.5:8080
      ETH_HOST: http://172.30.0.3:8545
      ETH_HOST_USER: test
      ETH_HOST_PASS: testAbc
      ETH_HOST_DISALLOWED_METHODS: eth_accounts,db_putString,db_getString,db_putHex,db_getHex
      DB_HOST: 172.30.0.4
      DB_USERNAME: ethproxy
      DB_PASSWORD: password
      DB_DATABASE: eth
      LOGLEVEL: DEBUG
    volumes:
      - xrproxy-config:/opt/uwsgi/conf
      - xrproxy-nginx:/etc/nginx
      - type: bind
        source: ./scripts
        target: /opt/scripts
    depends_on:
      - geth
      - postgresql
    networks:
      frontend_dev:
      backend_dev:
        ipv4_address: 172.30.0.6

networks:
  frontend_dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/24
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
  backend_dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"

volumes:
  snode-config:
  snode-data:
  eth-data:
  pgdata:
  xrproxy-config:
  xrproxy-nginx:
  scripts:
