version: "3.8"

services:
  snode:
    image: blocknetdx/servicenode:latest
    restart: unless-stopped
    environment:
      PUBLIC_IP: "${PUBLIC_IP}"
      RPC_USER: "${RPC_USER}"
      RPC_PASSWORD: "${RPC_PASSWORD}"
      SN_NAME: "${SN_NAME}"
      SN_ADDRESS: "${SN_ADDRESS}"
      SN_KEY: "${SN_KEY}"
    volumes:
      - /media/atcsecure/satassd4tb/snode-compose-test/config:/opt/blockchain/config
      - /media/atcsecure/satassd4tb/snode-compose-test/config:/opt/blockchain/data
    ports:
      - "41412"
      - "41414"
    networks:
      - backend

  geth:
    image: ethereum/client-go:latest
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
    volumes:
      - /media/atcsecure/satassd4tb/eth-compose-test/config:/chaindata
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --nousb
      - --rpc
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --graphql
      - --graphql.addr=0.0.0.0
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --datadir
      - "/chaindata"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
